### ISSUE TITLE
Use milliseconds instead of seconds

### ISSUE THREAD

**Issue by RangerMauve** [rwu823/stop.js#1]
This would be breaking and require a major version bump, but having millisecond-level control is useful for timing and it is the granularity that is supported by all the timing APIs (setTimeout, setInterval, etc..).

**Comment by rwu823** [comment]
If you need milliseconds It just be passed `stop(.1)`, that equal to `100ms`, the seconds will keep the code shorter in most case.

**Comment by rwu823** [comment]
And maybe in next:

```js
stop.sec(3)
// or
stop.ms(300)
```

**Comment by RangerMauve** [comment]
Fair enough

**Comment by eliperelman** [comment]
Still think the right answer is to use milliseconds instead of seconds. This keep the API consistent with standard methods. Not to mention, the bulk of timeouts in JS userland are probably under 1 second, which is the greater use case.

**Comment by rwu823** [comment]
@eliperelman 

Yes, good point. it will be changed in next roadmap.

What do you think? if this way
```js
stop.sec(3)
// or
stop.ms(300)
```

**Comment by lucianopf** [comment]
Sorry to interrupt, but I guess that only stop(300) using milliseconds it is enough to contemplate the API following the default standards.

adding auxiliary methods just to increase the readability will in fact increase the complexity of the solution, raising the learning curve.

It seems overreacting but if you consider the variety of methods in lodash you will realize how big the API would get if they decided to comtemplate things like that.

**Comment by rwu823** [comment]
@lucianopf 

hmm, it make sense

**Comment by bfred-it** [comment]
This one already supports milliseconds by default and is more flexible: https://github.com/sindresorhus/delay

**Comment by rwu823** [comment]
API already changes to `milliseconds `
